proc float Median(float $input[]) {

    int $size = size($input);
    float $Num[] = $input;

    $Num = sort($Num);

    float $median;
    
    if ($size % 2 == 0) {
        $median = ($Num[$size / 2 - 1] + $Num[$size / 2]) / 2.0;
    } 
    
    else {
        $median = $Num[int($size / 2)];
    }

    return $median;
}

proc float Mean(float $input[]) {
    float $sum = 0.0;

    for ($i = 0; $i < size($input); $i++) {
        $sum += $input[$i];
    }

    return ($sum / size($input));
}

proc float Power(float $input[]) {
    float $result = $input[0];

    for ($i = 1; $i < size($input); $i++) {
        $result = `pow $result $input[$i]`;
    }

    return $result;
}

proc float Multi(float $input[]) {
    float $result = $input[0];

    for ($i = 1; $i < size($input); $i++) {
        $result *= $input[$i];
    }

    return $result;
}

proc float Div(float $input[]) {
    float $result = $input[0];

    for ($i = 1; $i < size($input); $i++) {

        if ($input[$i] != 0) {
            $result /= $input[$i];
        } 

        else {
            error("Division by zero.");
        }
    }

    return $result;
}

proc float Sub(float $input[]) {
    float $result = $input[0];
    
    for ($i = 1; $i < size($input); $i++) {
        $result -= $input[$i];
    }

    return $result;
}

proc float Add(float $input[]) {
    float $result = 0.0;

    for ($i = 0; $i < size($input); $i++) {
        $result += $input[$i];
    }
    return $result;
}

global proc string Calculator(string $operation, float $nums[]) {

    string $numStr = "", $result = "", $opnWrd = "";

    for ($i = 0; $i < size($nums); $i++){
        $numStr += $nums[$i];

        if($i < size($nums) - 2){
            $numStr += ", ";
        }
        else if($i == size($nums) - 2) {
            $numStr += " and ";
        }
    }

    if ($operation == "Add" || $operation == "add") {
        $result = Add($nums);
        $opnWrd = "The sum of " ;
    } 
    else if ($operation == "Sub" || $operation == "sub") {
        $result = Sub($nums);
        $opnWrd = "The difference of ";
    } 
    else if ($operation == "Div" || $operation == "div") {
        $result = Div($nums);
        $opnWrd = "The quotient of ";
    } 
    else if ($operation == "Multi" || $operation == "multi") {
        $result = Multi($nums);
        $opnWrd = "The product of ";
    } 
    else if ($operation == "Power" || $operation == "power") {
        $result = Power($nums);
        $opnWrd = "The power of ";
    } 
    else if ($operation == "Mean" || $operation == "mean") {
        $result = Mean($nums);
        $opnWrd = "The mean of ";
    } 
    else if ($operation == "Median" || $operation == "median") {
        $result = Median($nums);
        $opnWrd = "The median of ";
    } 
    else {
        warning("Unknown operation: " + $operation + "\n");
    }

    return ($opnWrd + $numStr + " is " + $result + ".\n");
}