print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "C:/Users/Owner/DOCUME~1/UVU/UVU-AG~1/UNITYP~1/Assets/MAYAPR~1/Scenes/Models/CHARAC~1/Rain/Rain_v1.ma"`)
{		
	file -o "C:/Users/Owner/DOCUME~1/UVU/UVU-AG~1/UNITYP~1/Assets/MAYAPR~1/Scenes/Models/CHARAC~1/Rain/Rain_v1.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/Owner/DOCUME~1/UVU/UVU-AG~1/UNITYP~1/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "C:/Users/Owner/DOCUME~1/UVU/UVU-AG~1/UNITYP~1/Temp/CommandPipe";

$donepipeKill = `fopen "C:/Users/Owner/DOCUME~1/UVU/UVU-AG~1/UNITYP~1/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
